### ISSUE TITLE
Menu styles

### ISSUE THREAD

**Issue by tiborp** [brettsmason/luxe#119]
Hi Brett,

I noticed when using some custom menu's (for example in the footer), I had to overwrite quite a bit of the menu styles; I think it would be a good idea to specify (parts of) the styling a bit more, as in targeting the --primary menu only. For example: visibility, hover states, z-index and the like.

Cheers, Tibor

**Comment by brettsmason** [comment]
Yep agreed, I just haven't got round to it yet 😄 
I've been having to do that on most new projects, but haven't had time to put something together for the repo yet.

**Comment by tiborp** [comment]
👍

**Comment by brettsmason** [comment]
@tiborp I finally got round to rewriting the menu styles.
It now works by adding `menu--responsive` to the `<nav>` element. This keeps the default `.menu` class clean now.

Feel free to give it a try and let me know how you get on 😄

**Comment by tiborp** [comment]
Hi Brett,
Sorry for the late notice! Still haven't found the time for further testing this, but I'm pretty sure this will do the trick.

**Comment by brettsmason** [comment]
@tiborp That's ok was just having a clean up 😄 
I'm in the process of trying out Tailwind with the project so this may change again anyway in v2.
