### ISSUE TITLE
Keep having problems with npm run watch

### ISSUE THREAD

**Issue by snake2401** [brettsmason/luxe#244]
I seem to keep on having problems with running the npm commands... After nmp install i try to run the watch script but seems to get the error: 

npm ERR! code ELIFECYCLE
npm ERR! errno 1

I dont know if it 's got something to do with the luxe config, but my other luxe projects seem to have no problems...
 Cleared my caches, dit a reintall, updates node, run audit fixes...

**Comment by brettsmason** [comment]
Hi @snake2401 I've not experienced that myself.
Have you tried deleting the `node_modules` folder? Eg `rm -r node_modules`?
Is this a fresh copy of Luxe, or has it been modified at all?

**Comment by snake2401** [comment]
It was a local copy of a existing install. I copied the folder to another project. 

Already tried to remove the node_modules and installed it again using npm install. Didn’t work. 

Maybe I will create a second theme using a clean install and copy my modified files to it.

**Comment by snake2401** [comment]
Nope….
When a do a clean install I get warnings about my node version (see below). I am on node 9.11.1. What is the right version I must use?

npm WARN notsup Unsupported engine for cross-env@7.0.2: wanted: {"node":">=10.14","npm":">=6","yarn":">=1"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: cross-env@7.0.2
npm WARN notsup Unsupported engine for css-loader@4.3.0: wanted: {"node":">= 10.13.0"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: css-loader@4.3.0
npm WARN notsup Unsupported engine for eslint@6.8.0: wanted: {"node":"^8.10.0 || ^10.13.0 || >=11.10.1"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: eslint@6.8.0
npm WARN notsup Unsupported engine for fibers@4.0.3: wanted: {"node":">=10.0.0"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fibers@4.0.3
npm WARN notsup Unsupported engine for stylelint-config-wordpress@16.0.0: wanted: {"node":">=10"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: stylelint-config-wordpress@16.0.0
npm WARN notsup Unsupported engine for terser-webpack-plugin@4.2.1: wanted: {"node":">= 10.13.0"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: terser-webpack-plugin@4.2.1
npm WARN notsup Unsupported engine for fsevents@2.1.3: wanted: {"node":"^8.16.0 || ^10.6.0 || >=11.0.0"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fsevents@2.1.3
npm WARN notsup Unsupported engine for get-caller-file@2.0.5: wanted: {"node":"6.* || 8.* || >= 10.*"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: get-caller-file@2.0.5
npm WARN notsup Unsupported engine for camelcase@6.0.0: wanted: {"node":">=10"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: camelcase@6.0.0
npm WARN notsup Unsupported engine for semver@7.3.2: wanted: {"node":">=10"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.3.2
npm WARN notsup Unsupported engine for cli-width@3.0.0: wanted: {"node":">= 10"} (current: {"node":"9.11.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: cli-width@3.0.0
npm WARN notsup Unsupported engine for chalk@4.1.0: wanted: {"node":">=10"} (current: {"node":"9.11.1","npm":"6.14.4"})

**Comment by tiborp** [comment]
See error message:
**wanted: {"node":">=10.14"**,"npm":">=6","yarn":">=1"} (**current: {"node":"9.11.1"**,"npm":"6.14.4"})

**Comment by snake2401** [comment]
Yep I saw that, that was not the whole problem thought… Got it working now. The reason why I moved it to e new environment was because is downloaded e new version of Local. From there on my cpu went overboard (over 400%) when I ran the watch script and kept on compiling over and over… Turns out that the new local has a similar browsersync that conflicted rich de nmp script…

Oke, after ours of searching, I can continu on my project…
THX for the suggestions you guys

**Comment by brettsmason** [comment]
Glad you got it working, and thanks @tiborp for helping out 😃 
I'd suggest running at least the most up to date LTS version of node (12.18.4 at the moment).
