### ISSUE TITLE
Responsive menu implementation in other theme

### ISSUE THREAD

**Issue by tiborp** [brettsmason/luxe#285]
Hi Brett!

I am currently working on an _s based starter theme and trying to implement your responsive-menu.js. 

I have managed to add the proper BEM classes to the navigation, but somehow get the following error:
```
Uncaught ReferenceError: menuIcons is not defined
    at new ResponsiveMenu (responsive-menu.js:13)
```
Hope you can help me on my way solving this.

Cheers, Tibor

**Comment by brettsmason** [comment]
Hey Tibor!

So in V1 of the theme there was this:
https://github.com/brettsmason/luxe/blob/3170b4017151f275624fad0fd625f5a16287f9c6/app/functions-assets.php#L36

That was just a way to pass the svg to the menu, but you could just update the script to have that in line instead, or remove it.

Hope that helps!

**Comment by tiborp** [comment]
Aaah...of course! I totally missed that one :-S 
Thanks so much!!
