### ISSUE TITLE
Loading custom fonts

### ISSUE THREAD

**Issue by tiborp** [brettsmason/luxe#98]
Hi Brett,

I'm trying to use a custom font, but can't seem to get it working. I have added the font files to `resources/fonts`, and used 

`@font-face {
	font-family: "CadizWeb";font-style: normal;
	font-weight: 400;
	src:
		local("CadizWeb"),
		local("CadizWeb-Regular"),
		url("../../fonts/CadizWeb-Regular.woff2") format("woff2"),
		url("../../fonts/CadizWeb-Regular.woff") format("woff");
}
`

I can see the fonts are duplicated to the right directory in /public, but I think this also has to do something with the proper path to the custom fonts from `/public`.

Hope you can help..

**Comment by brettsmason** [comment]
@tiborp So it looks like its just a case that you have the wrong path.
The path is reletive to the stylesheet which is in `public/css` by default. So setting the path to `../fonts/` etc should solve the problem.
Give it a try and let me know if it works.

**Comment by tiborp** [comment]
Hmm..path is correct..I must be doing something else wrong. I'll look into it more and let you know.

**Comment by tiborp** [comment]
Arghh..I only had to adjust the order of the font settings... :-S
